.TH "source" 1 "13 Jan 2008" "Version 1.23.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
. - evaluate contents of file.
.PP
.SS "Synopsis"
\fC. FILENAME [ARGUMENTS...]\fP
.SS "Description"
Evaluates the commands of the specified file in the current shell. This is different from starting a new process to perform the commands (i.e. \fCfish < FILENAME\fP) since the commands will be evaluated by the current shell, which means that changes in environment variables, etc., will remain. If additional arguments are specified after the file name, they will be inserted into the $argv variable.
.PP
If no file is specified, or if the file name '-' is used, stdin will be read.
.PP
The return status of . is the return status of the last job to execute. If something goes wrong while opening or reading the file, . exits with a non-zero status.
.SS "Example"
\fC. ~/.fish\fP
.PP
causes fish to reread its initialization file. 
