.TH "prevd" 1 "13 Jan 2008" "Version 1.23.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prevd - move backward through directory history
.PP
.SS "Synopsis"
\fCprevd [-l | --list] [pos]\fP
.SS "Description"
\fCprevd\fP moves backwards \fCpos\fP positions in the history of visited directories; if the beginning of the history has been hit, a warning is printed. If the \fC-l\fP or \fC--list\fP flag is specified, the current history is also displayed. 
