.TH "return" 1 "13 Jan 2008" "Version 1.23.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
return - stop the innermost currently evaluated function
.PP
.SS "Synopsis"
\fCfunction NAME; [COMMANDS...;] return [STATUS]; [COMMANDS...;] end\fP
.SS "Description"
The \fCreturn\fP builtin is used to halt a currently running function. It is usually added inside of a conditional block such as an if statement or a \fCswitch\fP statement to conditionally stop the executing function and return to the caller, but it can also be used to specify the exit status of a function.
.PP
.IP "\(bu" 2
\fCSTATUS\fP is the return status of the function. If unspecified, the status is unchanged.
.PP
.SS "Example"
The following code is an implementation of the false command as a fish function
.PP
.PP
.nf

function false
	return 1
end
.fi
.PP
 
